"""
Please note that this file is generated by a script!
Please do not make any changes to this file!
"""
from ctypes import Structure, c_int

class BMSState(Structure):
	_pack_ = 1
	_fields_ = [
		("bms_state_0", c_int),
		("id", c_int),
		("state_time", c_int),
		("cells_0_mv", c_int),
		("cells_1_mv", c_int),
		("cells_2_mv", c_int),
		("cells_3_mv", c_int),
		("cells_4_mv", c_int),
		("cells_5_mv", c_int),
		("cells_6_mv", c_int),
		("cells_7_mv", c_int),
		("cells_8_mv", c_int),
		("bms_state", c_int),
		("current", c_int),
		("timer", c_int),
		("balancing", c_int),
		("stack_voltage", c_int),
		("pack_imbalance", c_int),
		("temp_0_", c_int),
		("temp_1_", c_int),
		("temp_2_", c_int),
		("genvar_0_", c_int),
		("genvar_1_", c_int),
		("genvar_2_", c_int),
		("genvar_3_", c_int),
		("ui", c_int),
		("sys_ctrl2", c_int),
		("SystemTime", c_int)]