"""
Please note that this file is generated by a script!
Please do not make any changes to this file!
"""
from ctypes import Structure, c_int

class NetNodeState(Structure):
	_pack_ = 1
	_fields_ = [
		("netnode", c_int),
		("id", c_int),
		("state_time", c_int),
		("genVar_0", c_int),
		("genVar_1", c_int),
		("genVar_2", c_int),
		("genVar_3", c_int),
		("status", c_int),
		("SystemTime", c_int)]