"""
Please note that this file is generated by a script!
Please do not make any changes to this file!
"""
from ctypes import Structure, c_int

class SCCDState(Structure):
	_pack_ = 1
	_fields_ = [
		("prototype", c_int),
		("id", c_int),
		("state_time", c_int),
		("cells[0].mV", c_int),
		("cells[0].mAh", c_int),
		("cells[1].mV", c_int),
		("cells[1].mAh", c_int),
		("cells[2].mV", c_int),
		("cells[2].mAh", c_int),
		("cells[3].mV", c_int),
		("cells[3].mAh", c_int),
		("cells[4].mV", c_int),
		("cells[4].mAh", c_int),
		("cells[5].mV", c_int),
		("cells[5].mAh", c_int),
		("cells[6].mV", c_int),
		("cells[6].mAh", c_int),
		("cells[7].mV", c_int),
		("cells[7].mAh", c_int),
		("cells[8].mV", c_int),
		("cells[8].mAh", c_int),
		("cellCharge", c_int),
		("cellDischarge", c_int),
		("Status", c_int),
		("SystemTime", c_int)]