# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                .*\.(ico|jpg|svg|png|user|xml|yaml|pro|pri|qrc|ui|dll|a|o|so|dll\.a|hex|mdl|slx|lock)|
                .*inc/.*|
                .*libs/.*
            )$
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                .*\.(ico|jpg|svg|png|user|xml|yaml|pro|pri|qrc|ui|dll|a|o|so|dll\.a|hex|mdl|slx|lock)|
                .*inc/.*|
                .*libs/.*
            )$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-case-conflict
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
# https://stackoverflow.com/a/61238571/8087342
# -   repo: local
#     hooks:
#     -   id: pylint
#         name: pylint
#         entry: pylint
#         language: system
#         types: [python]
#         require_serial: true
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a7
    hooks:
    -   id: pylint
        args:
        -   --output-format=colorized
        additional_dependencies:
        - boto3
        - pyudev
        - semantic-version
        - seaborn
        - nox
        - numpy
        - pandas
        - pyyaml
        - pendulum
