# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                .*\.(ico|jpg|svg|png|user|xml|yaml|pro|pri|qrc|ui|dll|a|o|so|dll\.a|hex|mdl|slx|lock)|
                .*inc/.*|
                .*libs/.*
            )$
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                .*\.(ico|jpg|svg|png|user|xml|yaml|pro|pri|qrc|ui|dll|a|o|so|dll\.a|hex|mdl|slx|lock)|
                .*inc/.*|
                .*libs/.*
            )$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-case-conflict