# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                .*\.(ico|jpg|svg|png|user|xml|yaml|pro|pri|qrc|ui|dll|a|o|so|dll\.a|hex|mdl|slx|lock)|
                .*inc/.*|
                .*libs/.*
            )$
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                .*\.(ico|jpg|svg|png|user|xml|yaml|pro|pri|qrc|ui|dll|a|o|so|dll\.a|hex|mdl|slx|lock)|
                .*inc/.*|
                .*libs/.*
            )$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-case-conflict
-   repo: https://github.com/alan-turing-institute/CleverCSV-pre-commit
    rev: v0.7.4
    hooks:
    -   id: clevercsv-standardize
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3
        exclude: |
            (?x)^(
                .*/dev_spec/.*|
                .*/DeviceSpecs/.*|
            )$
-   repo: https://github.com/PyCQA/pylint
    rev: v2.14.0
    hooks:
    -   id: pylint
        exclude: |
            (?x)^(
                .*/dev_spec/.*|
                .*/DeviceSpecs/.*|
            )$
        args:
            - --disable=R0801, W0511
        additional_dependencies:
            - flexsea
            - numpy
            - matplotlib
            - pyclibrary
            - cleo
        verbose: true
        files:  "" # No files
