"""
///
/// @file HabsoluteState.py
///
/// @brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// @core 0bad34709094958919bfe30e6c0ca13c7682c49a
///
/// @build df4ac791e9dd25df235f8ed979101d1d2e75b19b
///
/// @date 2020-06-22 14:42:45
///
/// @author Dephy, Inc.
"""
from ctypes import Structure, c_int

class HabsoluteState(Structure):
    _pack_ = 1
    _fields_ = [
        ("habsolute", c_int),
        ("id", c_int),
        ("state_time", c_int),
        ("ank_ang", c_int),
        ("ank_vel", c_int),
        ("adc_0", c_int),
        ("adc_1", c_int),
        ("adc_2", c_int),
        ("adc_3", c_int),
        ("adc_4", c_int),
        ("adc_5", c_int),
        ("adc_6", c_int),
        ("adc_7", c_int),
        ("genvar_0", c_int),
        ("genvar_1", c_int),
        ("genvar_2", c_int),
        ("genvar_3", c_int),
        ("status", c_int),
        ("SystemTime", c_int)]
