///
/// \file ActPack_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 23102a39a8baf714620361f08e7ae993abe06b7e
///
/// \build fb8c2409d776759b5191b6bacaabe51a49ade1cf
///
/// \date 2020-06-22 14:42:45
///
/// \author Dephy, Inc.

#ifndef ACTPACK_DEVICE_SPEC

	#define ACTPACK_DEVICE_SPEC
	#define ACTPACK_DEVICE_FIELD_COUNT 32

	#define ACTPACK_RIGID_POS                0
	#define ACTPACK_ID_POS                   1
	#define ACTPACK_STATE_TIME_POS           2
	#define ACTPACK_ACCELX_POS               3
	#define ACTPACK_ACCELY_POS               4
	#define ACTPACK_ACCELZ_POS               5
	#define ACTPACK_GYROX_POS                6
	#define ACTPACK_GYROY_POS                7
	#define ACTPACK_GYROZ_POS                8
	#define ACTPACK_MOT_ANG_POS              9
	#define ACTPACK_MOT_VEL_POS              10
	#define ACTPACK_MOT_ACC_POS              11
	#define ACTPACK_MOT_CUR_POS              12
	#define ACTPACK_MOT_VOLT_POS             13
	#define ACTPACK_BATT_VOLT_POS            14
	#define ACTPACK_BATT_CURR_POS            15
	#define ACTPACK_TEMPERATURE_POS          16
	#define ACTPACK_STATUS_MN_POS            17
	#define ACTPACK_STATUS_EX_POS            18
	#define ACTPACK_STATUS_RE_POS            19
	#define ACTPACK_GENVAR_0_POS             20
	#define ACTPACK_GENVAR_1_POS             21
	#define ACTPACK_GENVAR_2_POS             22
	#define ACTPACK_GENVAR_3_POS             23
	#define ACTPACK_GENVAR_4_POS             24
	#define ACTPACK_GENVAR_5_POS             25
	#define ACTPACK_GENVAR_6_POS             26
	#define ACTPACK_GENVAR_7_POS             27
	#define ACTPACK_GENVAR_8_POS             28
	#define ACTPACK_GENVAR_9_POS             29
	#define ACTPACK_ANK_ANG_POS              30
	#define ACTPACK_ANK_VEL_POS              31

#endif //ACTPACK_DEVICE_SPEC
