#ifndef ACTPACKPLUS_STRUCT_H
#define ACTPACKPLUS_STRUCT_H

/*
 * actpackplus_struct.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 * CORE:20640c2cc4ad040eed2aa76191f709854fc1595e
 * BUILD:afcc40f56e2a3c3254f831a89e0eab9db3660ba5
 *
 *
 * Specification File Created on: 2020-08-12 14:09:53
 * Author: Dephy, Inc.
 *
 */

#include "ActPackPlus_device_spec.h"
#include <stdio.h> 
#include <time.h> 
#include <string.h> 
#include <stdint.h> 

#include <stdbool.h> 

#define ACTPACKPLUS_SYSTEM_TIME_POS 32
#define ACTPACKPLUS_STRUCT_DEVICE_FIELD_COUNT 33
#define ACTPACKPLUS_LABEL_MAX_CHAR_LENGTH 12

//This is The Device fields*10 + deviceField+1. Ten is the max string length of 2^32 in decimal separated from commas
#define ACTPACKPLUS_DATA_STRING_LENGTH 364

#ifdef __cplusplus
extern "C"
{
#endif

#pragma pack(1)

struct ActPackPlusState
{
	int rigid;
	int id;
	int state_time;
	int accelx;
	int accely;
	int accelz;
	int gyrox;
	int gyroy;
	int gyroz;
	int mot_ang;
	int mot_vel;
	int mot_acc;
	int mot_cur;
	int mot_volt;
	int batt_volt;
	int batt_curr;
	int temperature;
	int status_mn;
	int status_ex;
	int status_re;
	int genvar_0;
	int genvar_1;
	int genvar_2;
	int genvar_3;
	int genvar_4;
	int genvar_5;
	int genvar_6;
	int genvar_7;
	int genvar_8;
	int genvar_9;
	int ank_ang;
	int ank_vel;

	//the system time
	int systemTime;
};

#pragma pack()

/// \brief Assigns the data in the buffer to the correct struct parameters
///
///@param ActPackPlus is the struct with the data to be set
///
///@param _deviceStateBuffer is the buffer containing the data to be assigned to the struct
///
///@param systemStartTime the time the system started. If unknown, use 0.
///
void ActPackPlusSetData(struct ActPackPlusState *actpackplus, uint32_t _deviceStateBuffer[], int systemStartTime);

/// \brief takes all data and places it into single, comma separated string
///
///@param ActPackPlus is the struct with the data to be placed in the string
///
///@param dataString is where the new string wll be placed 
///
void ActPackPlusDataToString(struct ActPackPlusState *actpackplus, char dataString[ACTPACKPLUS_DATA_STRING_LENGTH]);

/// \brief retrieves the string equivalent of all parameter names
///
///@param labels is the array of labels containing the parameter names
///
void ActPackPlusGetLabels(char labels[ACTPACKPLUS_STRUCT_DEVICE_FIELD_COUNT][ACTPACKPLUS_LABEL_MAX_CHAR_LENGTH]);

/// \brief retrieves the string equivalent of parameter names starting with state time.  Parameters 
/// prior to state time, such as id,  are not included. 
///
///@param labels is the array of labels containing the parameter names
///
int ActPackPlusGetLabelsForLog(char labels[ACTPACKPLUS_STRUCT_DEVICE_FIELD_COUNT][ACTPACKPLUS_LABEL_MAX_CHAR_LENGTH]);

/// \brief Places data from struct into an array.
///
///@param actpack the data to be converte to an array
///
///@param actpackDataArray the array in which to place the data
///
void ActPackPlusStructToDataArray(struct ActPackPlusState actpackplus, int32_t actpackplusDataArray[ACTPACKPLUS_STRUCT_DEVICE_FIELD_COUNT]);

/// \brief Get data based on data position from device communication.
///
///@param actpack the data to access
///
///@param dataPosition the position of data to access
///
///@param dataValid return false if requested data position is invalid
///
int GetActPackPlusDataByDataPosition( struct ActPackPlusState actpackplus, int dataPosition);

#ifdef __cplusplus
}//extern "C"
#endif

#endif ////ACTPACK_STRUCT_H
