///
/// \file ActPackPlus_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 2884905a73cad0c4467d0534b7f0cf4c6bbd71cf
///
/// \build 8aee30b182c15f582ae9f6b6150f0553f1afa8fb
///
/// \date 2021-05-10 10:03:07
///
/// \author Dephy, Inc.

#ifndef ACTPACKPLUS_DEVICE_SPEC

	#define ACTPACKPLUS_DEVICE_SPEC
	#define ACTPACKPLUS_DEVICE_FIELD_COUNT 32

	#define ACTPACKPLUS_RIGID_POS            0
	#define ACTPACKPLUS_ID_POS               1
	#define ACTPACKPLUS_STATE_TIME_POS       2
	#define ACTPACKPLUS_ACCELX_POS           3
	#define ACTPACKPLUS_ACCELY_POS           4
	#define ACTPACKPLUS_ACCELZ_POS           5
	#define ACTPACKPLUS_GYROX_POS            6
	#define ACTPACKPLUS_GYROY_POS            7
	#define ACTPACKPLUS_GYROZ_POS            8
	#define ACTPACKPLUS_MOT_ANG_POS          9
	#define ACTPACKPLUS_MOT_VEL_POS          10
	#define ACTPACKPLUS_MOT_ACC_POS          11
	#define ACTPACKPLUS_MOT_CUR_POS          12
	#define ACTPACKPLUS_MOT_VOLT_POS         13
	#define ACTPACKPLUS_BATT_VOLT_POS        14
	#define ACTPACKPLUS_BATT_CURR_POS        15
	#define ACTPACKPLUS_TEMPERATURE_POS      16
	#define ACTPACKPLUS_STATUS_MN_POS        17
	#define ACTPACKPLUS_STATUS_EX_POS        18
	#define ACTPACKPLUS_STATUS_RE_POS        19
	#define ACTPACKPLUS_GENVAR_0_POS         20
	#define ACTPACKPLUS_GENVAR_1_POS         21
	#define ACTPACKPLUS_GENVAR_2_POS         22
	#define ACTPACKPLUS_GENVAR_3_POS         23
	#define ACTPACKPLUS_GENVAR_4_POS         24
	#define ACTPACKPLUS_GENVAR_5_POS         25
	#define ACTPACKPLUS_GENVAR_6_POS         26
	#define ACTPACKPLUS_GENVAR_7_POS         27
	#define ACTPACKPLUS_GENVAR_8_POS         28
	#define ACTPACKPLUS_GENVAR_9_POS         29
	#define ACTPACKPLUS_ANK_ANG_POS          30
	#define ACTPACKPLUS_ANK_VEL_POS          31

#endif //ACTPACKPLUS_DEVICE_SPEC
