/*
 * BMS_device_spec.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 * Created on: 2020-07-30 00:34:38.334791
 * Author: Dephy, Inc.
 *
 */

#ifndef BMS_DEVICE_SPEC

	#define BMS_DEVICE_SPEC
	#define BMS_DEVICE_FIELD_COUNT 27

	#define	BMS_BMS_STATE_0_POS 0
	#define	BMS_ID_POS 1
	#define	BMS_STATE_TIME_POS 2
	#define	BMS_CELLS_0_MV_POS 3
	#define	BMS_CELLS_1_MV_POS 4
	#define	BMS_CELLS_2_MV_POS 5
	#define	BMS_CELLS_3_MV_POS 6
	#define	BMS_CELLS_4_MV_POS 7
	#define	BMS_CELLS_5_MV_POS 8
	#define	BMS_CELLS_6_MV_POS 9
	#define	BMS_CELLS_7_MV_POS 10
	#define	BMS_CELLS_8_MV_POS 11
	#define	BMS_BMS_STATE_POS 12
	#define	BMS_CURRENT_POS 13
	#define	BMS_TIMER_POS 14
	#define	BMS_BALANCING_POS 15
	#define	BMS_STACK_VOLTAGE_POS 16
	#define	BMS_PACK_IMBALANCE_POS 17
	#define	BMS_TEMP_0_POS 18
	#define	BMS_TEMP_1_POS 19
	#define	BMS_TEMP_2_POS 20
	#define	BMS_GENVAR_0_POS 21
	#define	BMS_GENVAR_1_POS 22
	#define	BMS_GENVAR_2_POS 23
	#define	BMS_GENVAR_3_POS 24
	#define	BMS_UI_POS 25
	#define	BMS_SYS_CTRL2_POS 26

#endif //BMS_DEVICE_SPEC
