///
/// \file EB603_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 23102a39a8baf714620361f08e7ae993abe06b7e
///
/// \build fb8c2409d776759b5191b6bacaabe51a49ade1cf
///
/// \date 2021-06-03 14:31:33
///
/// \author Dephy, Inc.

#ifndef EB603_DEVICE_SPEC

	#define EB603_DEVICE_SPEC
	#define EB603_DEVICE_FIELD_COUNT 59

	#define EB603_RIGID_POS                  0
	#define EB603_ID_POS                     1
	#define EB603_STATE_TIME_POS             2
	#define EB603_ACCELX_POS                 3
	#define EB603_ACCELY_POS                 4
	#define EB603_ACCELZ_POS                 5
	#define EB603_GYROX_POS                  6
	#define EB603_GYROY_POS                  7
	#define EB603_GYROZ_POS                  8
	#define EB603_MOT_ANG_POS                9
	#define EB603_MOT_VEL_POS                10
	#define EB603_MOT_ACC_POS                11
	#define EB603_MOT_CUR_POS                12
	#define EB603_MOT_VOLT_POS               13
	#define EB603_BATT_VOLT_POS              14
	#define EB603_BATT_CURR_POS              15
	#define EB603_TEMPERATURE_POS            16
	#define EB603_STATUS_MN_POS              17
	#define EB603_STATUS_EX_POS              18
	#define EB603_STATUS_RE_POS              19
	#define EB603_GENVAR_0_POS               20
	#define EB603_GENVAR_1_POS               21
	#define EB603_GENVAR_2_POS               22
	#define EB603_GENVAR_3_POS               23
	#define EB603_GENVAR_4_POS               24
	#define EB603_GENVAR_5_POS               25
	#define EB603_GENVAR_6_POS               26
	#define EB603_GENVAR_7_POS               27
	#define EB603_GENVAR_8_POS               28
	#define EB603_GENVAR_9_POS               29
	#define EB603_GENVAR_10_POS              30
	#define EB603_GENVAR_11_POS              31
	#define EB603_GENVAR_12_POS              32
	#define EB603_GENVAR_13_POS              33
	#define EB603_GENVAR_14_POS              34
	#define EB603_ANK_ANG_POS                35
	#define EB603_ANK_VEL_POS                36
	#define EB603_SHANK_ANG_POS              37
	#define EB603_SHANK_VEL_POS              38
	#define EB603_GLOBAL_SHANK_ANG_POS       39
	#define EB603_ANK_POS_X_POS              40
	#define EB603_ANK_POS_Y_POS              41
	#define EB603_ANK_POS_Z_POS              42
	#define EB603_ANK_LINEAR_VEL_X_POS       43
	#define EB603_ANK_LINEAR_VEL_Y_POS       44
	#define EB603_ANK_LINEAR_VEL_Z_POS       45
	#define EB603_MOT_FROM_ANK_POS           46
	#define EB603_ANK_FROM_MOT_POS           47
	#define EB603_TRANS_RATIO_POS            48
	#define EB603_ANK_TORQUE_POS             49
	#define EB603_PEAK_ANK_TORQUE_POS        50
	#define EB603_STEP_ENERGY_POS            51
	#define EB603_STEP_COUNT_POS             52
	#define EB603_STEP_TIME_POS              53
	#define EB603_GAIT_STATE_POS             54
	#define EB603_INTERMEDIATE_STATE_POS     55
	#define EB603_MOVEMENT_POS               56
	#define EB603_SPEED_POS                  57
	#define EB603_INCLINE_POS                58

#endif //EB603_DEVICE_SPEC
