/*
 * Exo_device_spec.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 * Created on: 2020-07-30 16:02:55.214745
 * Author: Dephy, Inc.
 *
 */

#ifndef EXO_DEVICE_SPEC

	#define EXO_DEVICE_SPEC
	#define EXO_DEVICE_FIELD_COUNT 35

	#define	EXO_RIGID_POS 0
	#define	EXO_ID_POS 1
	#define	EXO_STATE_TIME_POS 2
	#define	EXO_ACCELX_POS 3
	#define	EXO_ACCELY_POS 4
	#define	EXO_ACCELZ_POS 5
	#define	EXO_GYROX_POS 6
	#define	EXO_GYROY_POS 7
	#define	EXO_GYROZ_POS 8
	#define	EXO_MOT_ANG_POS 9
	#define	EXO_MOT_VEL_POS 10
	#define	EXO_MOT_ACC_POS 11
	#define	EXO_MOT_CUR_POS 12
	#define	EXO_MOT_VOLT_POS 13
	#define	EXO_BATT_VOLT_POS 14
	#define	EXO_BATT_CURR_POS 15
	#define	EXO_TEMPERATURE_POS 16
	#define	EXO_STATUS_MN_POS 17
	#define	EXO_STATUS_EX_POS 18
	#define	EXO_STATUS_RE_POS 19
	#define	EXO_GENVAR_0_POS 20
	#define	EXO_GENVAR_1_POS 21
	#define	EXO_GENVAR_2_POS 22
	#define	EXO_GENVAR_3_POS 23
	#define	EXO_GENVAR_4_POS 24
	#define	EXO_GENVAR_5_POS 25
	#define	EXO_GENVAR_6_POS 26
	#define	EXO_GENVAR_7_POS 27
	#define	EXO_GENVAR_8_POS 28
	#define	EXO_GENVAR_9_POS 29
	#define	EXO_ANK_ANG_POS 30
	#define	EXO_ANK_VEL_POS 31
	#define	EXO_SHANK_ANG_POS 32
	#define	EXO_SHANK_VEL_POS 33
	#define	EXO_GLOBAL_SHANK_ANG_POS 34

#endif //EXO_DEVICE_SPEC
