#ifndef HABSOLUTE_STRUCT_H
#define HABSOLUTE_STRUCT_H
/*
 * habsolute_struct.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 *
 *  Created on: 2020-04-06 21:10:22.871710
 *      Author: Dephy Inc
 */

#include "Habsolute_device_spec.h "
#include <sstream> 
#include <stdio.h> 
#include <string> 

#include <ctime> 

#define HABSOLUTE_SYSTEM_TIME_POS 18
#define HABSOLUTE_STRUCT_DEVICE_FIELD_COUNT 19

struct HabsoluteState 
 { 

	int habsolute_habsolute;
	int habsolute_id;
	int habsolute_state_time;
	int habsolute_ank_ang;
	int habsolute_ank_vel;
	int habsolute_adc_0;
	int habsolute_adc_1;
	int habsolute_adc_2;
	int habsolute_adc_3;
	int habsolute_adc_4;
	int habsolute_adc_5;
	int habsolute_adc_6;
	int habsolute_adc_7;
	int habsolute_genvar_0;
	int habsolute_genvar_1;
	int habsolute_genvar_2;
	int habsolute_genvar_3;
	int habsolute_status;
	//the system time
	clock_t systemTime;
	uint32_t deviceData[HABSOLUTE_STRUCT_DEVICE_FIELD_COUNT];

	// sets the data.  Requires system start time.  If unavailable, set to 0
	void setData(uint32_t _deviceStateBuffer[], clock_t systemStartTime) 
 	{
		habsolute_habsolute=_deviceStateBuffer[HABSOLUTE_HABSOLUTE_POS ];
		deviceData[HABSOLUTE_HABSOLUTE_POS ]=_deviceStateBuffer[HABSOLUTE_HABSOLUTE_POS ];
		habsolute_id=_deviceStateBuffer[HABSOLUTE_ID_POS ];
		deviceData[HABSOLUTE_ID_POS ]=_deviceStateBuffer[HABSOLUTE_ID_POS ];
		habsolute_state_time=_deviceStateBuffer[HABSOLUTE_STATE_TIME_POS ];
		deviceData[HABSOLUTE_STATE_TIME_POS ]=_deviceStateBuffer[HABSOLUTE_STATE_TIME_POS ];
		habsolute_ank_ang=_deviceStateBuffer[HABSOLUTE_ANK_ANG_POS ];
		deviceData[HABSOLUTE_ANK_ANG_POS ]=_deviceStateBuffer[HABSOLUTE_ANK_ANG_POS ];
		habsolute_ank_vel=_deviceStateBuffer[HABSOLUTE_ANK_VEL_POS ];
		deviceData[HABSOLUTE_ANK_VEL_POS ]=_deviceStateBuffer[HABSOLUTE_ANK_VEL_POS ];
		habsolute_adc_0=_deviceStateBuffer[HABSOLUTE_ADC_0_POS ];
		deviceData[HABSOLUTE_ADC_0_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_0_POS ];
		habsolute_adc_1=_deviceStateBuffer[HABSOLUTE_ADC_1_POS ];
		deviceData[HABSOLUTE_ADC_1_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_1_POS ];
		habsolute_adc_2=_deviceStateBuffer[HABSOLUTE_ADC_2_POS ];
		deviceData[HABSOLUTE_ADC_2_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_2_POS ];
		habsolute_adc_3=_deviceStateBuffer[HABSOLUTE_ADC_3_POS ];
		deviceData[HABSOLUTE_ADC_3_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_3_POS ];
		habsolute_adc_4=_deviceStateBuffer[HABSOLUTE_ADC_4_POS ];
		deviceData[HABSOLUTE_ADC_4_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_4_POS ];
		habsolute_adc_5=_deviceStateBuffer[HABSOLUTE_ADC_5_POS ];
		deviceData[HABSOLUTE_ADC_5_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_5_POS ];
		habsolute_adc_6=_deviceStateBuffer[HABSOLUTE_ADC_6_POS ];
		deviceData[HABSOLUTE_ADC_6_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_6_POS ];
		habsolute_adc_7=_deviceStateBuffer[HABSOLUTE_ADC_7_POS ];
		deviceData[HABSOLUTE_ADC_7_POS ]=_deviceStateBuffer[HABSOLUTE_ADC_7_POS ];
		habsolute_genvar_0=_deviceStateBuffer[HABSOLUTE_GENVAR_0_POS ];
		deviceData[HABSOLUTE_GENVAR_0_POS ]=_deviceStateBuffer[HABSOLUTE_GENVAR_0_POS ];
		habsolute_genvar_1=_deviceStateBuffer[HABSOLUTE_GENVAR_1_POS ];
		deviceData[HABSOLUTE_GENVAR_1_POS ]=_deviceStateBuffer[HABSOLUTE_GENVAR_1_POS ];
		habsolute_genvar_2=_deviceStateBuffer[HABSOLUTE_GENVAR_2_POS ];
		deviceData[HABSOLUTE_GENVAR_2_POS ]=_deviceStateBuffer[HABSOLUTE_GENVAR_2_POS ];
		habsolute_genvar_3=_deviceStateBuffer[HABSOLUTE_GENVAR_3_POS ];
		deviceData[HABSOLUTE_GENVAR_3_POS ]=_deviceStateBuffer[HABSOLUTE_GENVAR_3_POS ];
		habsolute_status=_deviceStateBuffer[HABSOLUTE_STATUS_POS ];
		deviceData[HABSOLUTE_STATUS_POS ]=_deviceStateBuffer[HABSOLUTE_STATUS_POS ];

		systemTime= systemStartTime-clock();
		deviceData[HABSOLUTE_SYSTEM_TIME_POS]=systemTime;
	};

	void sendToStream(std::stringstream &ss) 
 	{
		ss << habsolute_habsolute <<",";
		ss << habsolute_id <<",";
		ss << habsolute_state_time <<",";
		ss << habsolute_ank_ang <<",";
		ss << habsolute_ank_vel <<",";
		ss << habsolute_adc_0 <<",";
		ss << habsolute_adc_1 <<",";
		ss << habsolute_adc_2 <<",";
		ss << habsolute_adc_3 <<",";
		ss << habsolute_adc_4 <<",";
		ss << habsolute_adc_5 <<",";
		ss << habsolute_adc_6 <<",";
		ss << habsolute_adc_7 <<",";
		ss << habsolute_genvar_0 <<",";
		ss << habsolute_genvar_1 <<",";
		ss << habsolute_genvar_2 <<",";
		ss << habsolute_genvar_3 <<",";
		ss << habsolute_status <<",";
		ss<<systemTime<<",";
	};

	 static void GetLabels(std::string *labels) 
 	{
		labels[HABSOLUTE_HABSOLUTE_POS]= "habsolute";
		labels[HABSOLUTE_ID_POS]= "id";
		labels[HABSOLUTE_STATE_TIME_POS]= "state_time";
		labels[HABSOLUTE_ANK_ANG_POS]= "ank_ang";
		labels[HABSOLUTE_ANK_VEL_POS]= "ank_vel";
		labels[HABSOLUTE_ADC_0_POS]= "adc_0";
		labels[HABSOLUTE_ADC_1_POS]= "adc_1";
		labels[HABSOLUTE_ADC_2_POS]= "adc_2";
		labels[HABSOLUTE_ADC_3_POS]= "adc_3";
		labels[HABSOLUTE_ADC_4_POS]= "adc_4";
		labels[HABSOLUTE_ADC_5_POS]= "adc_5";
		labels[HABSOLUTE_ADC_6_POS]= "adc_6";
		labels[HABSOLUTE_ADC_7_POS]= "adc_7";
		labels[HABSOLUTE_GENVAR_0_POS]= "genVar_0";
		labels[HABSOLUTE_GENVAR_1_POS]= "genVar_1";
		labels[HABSOLUTE_GENVAR_2_POS]= "genVar_2";
		labels[HABSOLUTE_GENVAR_3_POS]= "genVar_3";
		labels[HABSOLUTE_STATUS_POS]= "status";
		labels[HABSOLUTE_SYSTEM_TIME_POS]="sys_time";
	};
}; 
#endif ////HABSOLUTE_STRUCT_H
