///
/// \file Habsolute_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 22b8056df896ab8048743e6c2f68f7fa9b2d48f8
///
/// \build 124d2903b0d2485f7864371fa16857f7eda2d9b9
///
/// \date 2020-06-22 14:42:45
///
/// \author Dephy, Inc.

#ifndef HABSOLUTE_DEVICE_SPEC

	#define HABSOLUTE_DEVICE_SPEC
	#define HABSOLUTE_DEVICE_FIELD_COUNT 18

	#define HABSOLUTE_HABSOLUTE_POS          0
	#define HABSOLUTE_ID_POS                 1
	#define HABSOLUTE_STATE_TIME_POS         2
	#define HABSOLUTE_ANK_ANG_POS            3
	#define HABSOLUTE_ANK_VEL_POS            4
	#define HABSOLUTE_ADC_0_POS              5
	#define HABSOLUTE_ADC_1_POS              6
	#define HABSOLUTE_ADC_2_POS              7
	#define HABSOLUTE_ADC_3_POS              8
	#define HABSOLUTE_ADC_4_POS              9
	#define HABSOLUTE_ADC_5_POS              10
	#define HABSOLUTE_ADC_6_POS              11
	#define HABSOLUTE_ADC_7_POS              12
	#define HABSOLUTE_GENVAR_0_POS           13
	#define HABSOLUTE_GENVAR_1_POS           14
	#define HABSOLUTE_GENVAR_2_POS           15
	#define HABSOLUTE_GENVAR_3_POS           16
	#define HABSOLUTE_STATUS_POS             17

#endif //HABSOLUTE_DEVICE_SPEC
