///
/// \file MD11_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 2884905a73cad0c4467d0534b7f0cf4c6bbd71cf
///
/// \build 8aee30b182c15f582ae9f6b6150f0553f1afa8fb
///
/// \date 2021-12-16 14:53:15
///
/// \author Dephy, Inc.

#ifndef MD11_DEVICE_SPEC

	#define MD11_DEVICE_SPEC
	#define MD11_DEVICE_FIELD_COUNT 49

	#define MD11_RIGID_POS                   0
	#define MD11_ID_POS                      1
	#define MD11_STATE_TIME_POS              2
	#define MD11_ACCELX_POS                  3
	#define MD11_ACCELY_POS                  4
	#define MD11_ACCELZ_POS                  5
	#define MD11_GYROX_POS                   6
	#define MD11_GYROY_POS                   7
	#define MD11_GYROZ_POS                   8
	#define MD11_MOT_ANG_POS                 9
	#define MD11_MOT_VEL_POS                 10
	#define MD11_MOT_ACC_POS                 11
	#define MD11_MOT_CUR_POS                 12
	#define MD11_MOT_VOLT_POS                13
	#define MD11_BATT_VOLT_POS               14
	#define MD11_BATT_CURR_POS               15
	#define MD11_TEMPERATURE_POS             16
	#define MD11_STATUS_MN_POS               17
	#define MD11_STATUS_EX_POS               18
	#define MD11_STATUS_RE_POS               19
	#define MD11_GENVAR_0_POS                20
	#define MD11_GENVAR_1_POS                21
	#define MD11_GENVAR_2_POS                22
	#define MD11_GENVAR_3_POS                23
	#define MD11_GENVAR_4_POS                24
	#define MD11_GENVAR_5_POS                25
	#define MD11_GENVAR_6_POS                26
	#define MD11_GENVAR_7_POS                27
	#define MD11_GENVAR_8_POS                28
	#define MD11_GENVAR_9_POS                29
	#define MD11_GENVAR_10_POS               30
	#define MD11_GENVAR_11_POS               31
	#define MD11_GENVAR_12_POS               32
	#define MD11_GENVAR_13_POS               33
	#define MD11_GENVAR_14_POS               34
	#define MD11_ANK_ANG_POS                 35
	#define MD11_ANK_VEL_POS                 36
	#define MD11_SHANK_ANG_POS               37
	#define MD11_SHANK_VEL_POS               38
	#define MD11_GLOBAL_SHANK_ANG_POS        39
	#define MD11_MOT_FROM_ANK_POS            40
	#define MD11_ANK_FROM_MOT_POS            41
	#define MD11_TRANS_RATIO_POS             42
	#define MD11_ANK_TORQUE_POS              43
	#define MD11_STEP_COUNT_POS              44
	#define MD11_STEP_TIME_POS               45
	#define MD11_GAIT_STATE_POS              46
	#define MD11_INTERMEDIATE_STATE_POS      47
	#define MD11_MOVEMENT_POS                48

#endif //MD11_DEVICE_SPEC
