#ifndef MD30_STRUCT_H
#define MD30_STRUCT_H

///
/// \file md30_struct.h
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core ffa7a6ed3a4c8bda8afc14abb85420b5f38e0de3
///
/// \build c6af82e4320f262c91106ef700d16ccb9f19751e
///
/// \date 2022-09-28 10:43:14
///
/// \author Dephy, Inc.

#include "MD30_device_spec.h"
#include <stdio.h>
#include <time.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#define MD30_SYSTEM_TIME_POS 57
#define MD30_STRUCT_DEVICE_FIELD_COUNT 58
#define MD30_LABEL_MAX_CHAR_LENGTH 19

/// This is The Device fields * 10 + deviceField + 1. Ten is the max string length of 2^32 in
/// decimal separated from commas
#define MD30_DATA_STRING_LENGTH 639

#ifdef __cplusplus
extern "C"
{
#endif

#pragma pack(1)

struct MD30State
{
	int rigid;
	int id;
	int state_time;
	int accelx;
	int accely;
	int accelz;
	int gyrox;
	int gyroy;
	int gyroz;
	int mot_ang;
	int mot_vel;
	int mot_acc;
	int mot_cur;
	int mot_volt;
	int batt_volt;
	int batt_curr;
	int temperature;
	int status_mn;
	int status_ex;
	int status_re;
	int genvar_0;
	int genvar_1;
	int genvar_2;
	int genvar_3;
	int genvar_4;
	int genvar_5;
	int genvar_6;
	int genvar_7;
	int genvar_8;
	int genvar_9;
	int genvar_10;
	int genvar_11;
	int genvar_12;
	int genvar_13;
	int genvar_14;
	int ank_ang;
	int ank_vel;
	int shank_ang;
	int shank_vel;
	int global_shank_ang;
	int ank_pos_x;
	int ank_pos_y;
	int ank_pos_z;
	int ank_linear_vel_x;
	int ank_linear_vel_y;
	int ank_linear_vel_z;
	int mot_from_ank;
	int ank_from_mot;
	int trans_ratio;
	int ank_torque;
	int exo_step_power;
	int step_count;
	int step_time;
	int gait_state;
	int intermediate_state;
	int movement;
	int toe_whip;
	int systemTime; /// System time
};

#pragma pack()

///
/// \brief Assigns the data in the buffer to the correct struct parameters
///
/// \param MD30 is the struct with the data to be set
///
/// \param _deviceStateBuffer is the buffer containing the data to be assigned to the struct
///
/// \param systemStartTime the time the system started. If unknown, use 0.
///
void MD30SetData(struct MD30State *md30, const uint32_t _deviceStateBuffer[], int systemStartTime);

///
/// \brief takes all data and places it into single, comma separated string
///
/// \param MD30 is the struct with the data to be placed in the string
///
/// \param dataString is where the new string wll be placed
///
void MD30DataToString(struct MD30State *md30, char dataString[MD30_DATA_STRING_LENGTH]);

///
/// \brief retrieves the string equivalent of all parameter names
///
/// \param labels is the array of labels containing the parameter names
///
void MD30GetLabels(char labels[MD30_STRUCT_DEVICE_FIELD_COUNT][MD30_LABEL_MAX_CHAR_LENGTH]);

///
/// \brief retrieves the string equivalent of parameter names starting with state time.
/// Parameters prior to state time, such as id, are not included.
///
/// \param labels is the array of labels containing the parameter names
///
int MD30GetLabelsForLog(char labels[MD30_STRUCT_DEVICE_FIELD_COUNT][MD30_LABEL_MAX_CHAR_LENGTH]);

///
/// \brief Places data from struct into an array.
///
/// \param md30 the data to be converted to an array
///
/// \param md30DataArray the array in which to place the data
///
void MD30StructToDataArray(struct MD30State md30, int32_t md30DataArray[MD30_STRUCT_DEVICE_FIELD_COUNT]);

///
/// \brief Get data based on data position from device communication.
///
/// \param md30 the data to access
///
/// \param dataPosition the position of data to access
///
/// \param dataValid return false if requested data position is invalid
///
int GetMD30DataByDataPosition( struct MD30State md30, int dataPosition);

#ifdef __cplusplus
} //extern "C"
#endif

#endif //MD30_STRUCT_H
