///
/// \file MD30_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 4fe8d03c976206777d13309232f04ddf8ff81836
///
/// \build a65a38d9383e1ab54f6f440660c1e07b2e86c7ee
///
/// \date 2022-09-28 10:43:14
///
/// \author Dephy, Inc.

#ifndef MD30_DEVICE_SPEC

	#define MD30_DEVICE_SPEC
	#define MD30_DEVICE_FIELD_COUNT 57

	#define MD30_RIGID_POS                   0
	#define MD30_ID_POS                      1
	#define MD30_STATE_TIME_POS              2
	#define MD30_ACCELX_POS                  3
	#define MD30_ACCELY_POS                  4
	#define MD30_ACCELZ_POS                  5
	#define MD30_GYROX_POS                   6
	#define MD30_GYROY_POS                   7
	#define MD30_GYROZ_POS                   8
	#define MD30_MOT_ANG_POS                 9
	#define MD30_MOT_VEL_POS                 10
	#define MD30_MOT_ACC_POS                 11
	#define MD30_MOT_CUR_POS                 12
	#define MD30_MOT_VOLT_POS                13
	#define MD30_BATT_VOLT_POS               14
	#define MD30_BATT_CURR_POS               15
	#define MD30_TEMPERATURE_POS             16
	#define MD30_STATUS_MN_POS               17
	#define MD30_STATUS_EX_POS               18
	#define MD30_STATUS_RE_POS               19
	#define MD30_GENVAR_0_POS                20
	#define MD30_GENVAR_1_POS                21
	#define MD30_GENVAR_2_POS                22
	#define MD30_GENVAR_3_POS                23
	#define MD30_GENVAR_4_POS                24
	#define MD30_GENVAR_5_POS                25
	#define MD30_GENVAR_6_POS                26
	#define MD30_GENVAR_7_POS                27
	#define MD30_GENVAR_8_POS                28
	#define MD30_GENVAR_9_POS                29
	#define MD30_GENVAR_10_POS               30
	#define MD30_GENVAR_11_POS               31
	#define MD30_GENVAR_12_POS               32
	#define MD30_GENVAR_13_POS               33
	#define MD30_GENVAR_14_POS               34
	#define MD30_ANK_ANG_POS                 35
	#define MD30_ANK_VEL_POS                 36
	#define MD30_SHANK_ANG_POS               37
	#define MD30_SHANK_VEL_POS               38
	#define MD30_GLOBAL_SHANK_ANG_POS        39
	#define MD30_ANK_POS_X_POS               40
	#define MD30_ANK_POS_Y_POS               41
	#define MD30_ANK_POS_Z_POS               42
	#define MD30_ANK_LINEAR_VEL_X_POS        43
	#define MD30_ANK_LINEAR_VEL_Y_POS        44
	#define MD30_ANK_LINEAR_VEL_Z_POS        45
	#define MD30_MOT_FROM_ANK_POS            46
	#define MD30_ANK_FROM_MOT_POS            47
	#define MD30_TRANS_RATIO_POS             48
	#define MD30_ANK_TORQUE_POS              49
	#define MD30_EXO_STEP_POWER_POS          50
	#define MD30_STEP_COUNT_POS              51
	#define MD30_STEP_TIME_POS               52
	#define MD30_GAIT_STATE_POS              53
	#define MD30_INTERMEDIATE_STATE_POS      54
	#define MD30_MOVEMENT_POS                55
	#define MD30_TOE_WHIP_POS                56

#endif //MD30_DEVICE_SPEC
