///
/// \file NetNode_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 22b8056df896ab8048743e6c2f68f7fa9b2d48f8
///
/// \build 124d2903b0d2485f7864371fa16857f7eda2d9b9
///
/// \date 2020-06-22 14:42:45
///
/// \author Dephy, Inc.

#ifndef NETNODE_DEVICE_SPEC

	#define NETNODE_DEVICE_SPEC
	#define NETNODE_DEVICE_FIELD_COUNT 8

	#define NETNODE_NETNODE_POS              0
	#define NETNODE_ID_POS                   1
	#define NETNODE_STATE_TIME_POS           2
	#define NETNODE_GENVAR_0_POS             3
	#define NETNODE_GENVAR_1_POS             4
	#define NETNODE_GENVAR_2_POS             5
	#define NETNODE_GENVAR_3_POS             6
	#define NETNODE_STATUS_POS               7

#endif //NETNODE_DEVICE_SPEC
