///
/// \file NetNode_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 2884905a73cad0c4467d0534b7f0cf4c6bbd71cf
///
/// \build 8aee30b182c15f582ae9f6b6150f0553f1afa8fb
///
/// \date 2020-06-22 14:42:45
///
/// \author Dephy, Inc.

#ifndef NETNODE_DEVICE_SPEC

	#define NETNODE_DEVICE_SPEC
	#define NETNODE_DEVICE_FIELD_COUNT 8

	#define NETNODE_NETNODE_POS              0
	#define NETNODE_ID_POS                   1
	#define NETNODE_STATE_TIME_POS           2
	#define NETNODE_GENVAR_0_POS             3
	#define NETNODE_GENVAR_1_POS             4
	#define NETNODE_GENVAR_2_POS             5
	#define NETNODE_GENVAR_3_POS             6
	#define NETNODE_STATUS_POS               7

#endif //NETNODE_DEVICE_SPEC
