///
/// \file NewBoo_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 2884905a73cad0c4467d0534b7f0cf4c6bbd71cf
///
/// \build 8aee30b182c15f582ae9f6b6150f0553f1afa8fb
///
/// \date 2022-01-04 16:18:23
///
/// \author Dephy, Inc.

#ifndef NEWBOO_DEVICE_SPEC

	#define NEWBOO_DEVICE_SPEC
	#define NEWBOO_DEVICE_FIELD_COUNT 60

	#define NEWBOO_RIGID_POS                 0
	#define NEWBOO_ID_POS                    1
	#define NEWBOO_STATE_TIME_POS            2
	#define NEWBOO_ACCELX_POS                3
	#define NEWBOO_ACCELY_POS                4
	#define NEWBOO_ACCELZ_POS                5
	#define NEWBOO_GYROX_POS                 6
	#define NEWBOO_GYROY_POS                 7
	#define NEWBOO_GYROZ_POS                 8
	#define NEWBOO_MOT_ANG_POS               9
	#define NEWBOO_MOT_VEL_POS               10
	#define NEWBOO_MOT_ACC_POS               11
	#define NEWBOO_MOT_CUR_POS               12
	#define NEWBOO_MOT_VOLT_POS              13
	#define NEWBOO_BATT_VOLT_POS             14
	#define NEWBOO_BATT_CURR_POS             15
	#define NEWBOO_TEMPERATURE_POS           16
	#define NEWBOO_STATUS_MN_POS             17
	#define NEWBOO_STATUS_EX_POS             18
	#define NEWBOO_STATUS_RE_POS             19
	#define NEWBOO_GENVAR_0_POS              20
	#define NEWBOO_GENVAR_1_POS              21
	#define NEWBOO_GENVAR_2_POS              22
	#define NEWBOO_GENVAR_3_POS              23
	#define NEWBOO_GENVAR_4_POS              24
	#define NEWBOO_GENVAR_5_POS              25
	#define NEWBOO_GENVAR_6_POS              26
	#define NEWBOO_GENVAR_7_POS              27
	#define NEWBOO_GENVAR_8_POS              28
	#define NEWBOO_GENVAR_9_POS              29
	#define NEWBOO_GENVAR_10_POS             30
	#define NEWBOO_GENVAR_11_POS             31
	#define NEWBOO_GENVAR_12_POS             32
	#define NEWBOO_GENVAR_13_POS             33
	#define NEWBOO_GENVAR_14_POS             34
	#define NEWBOO_ANK_ANG_POS               35
	#define NEWBOO_ANK_VEL_POS               36
	#define NEWBOO_SHANK_ANG_POS             37
	#define NEWBOO_SHANK_VEL_POS             38
	#define NEWBOO_GLOBAL_SHANK_ANG_POS      39
	#define NEWBOO_ANK_POS_X_POS             40
	#define NEWBOO_ANK_POS_Y_POS             41
	#define NEWBOO_ANK_POS_Z_POS             42
	#define NEWBOO_ANK_LINEAR_VEL_X_POS      43
	#define NEWBOO_ANK_LINEAR_VEL_Y_POS      44
	#define NEWBOO_ANK_LINEAR_VEL_Z_POS      45
	#define NEWBOO_MOT_FROM_ANK_POS          46
	#define NEWBOO_ANK_FROM_MOT_POS          47
	#define NEWBOO_TRANS_RATIO_POS           48
	#define NEWBOO_ANK_TORQUE_POS            49
	#define NEWBOO_AVG_ANK_TORQUE_POS        50
	#define NEWBOO_EXO_STEP_POWER_POS        51
	#define NEWBOO_BATTERY_STEP_POWER_POS    52
	#define NEWBOO_STEP_COUNT_POS            53
	#define NEWBOO_STEP_TIME_POS             54
	#define NEWBOO_GAIT_STATE_POS            55
	#define NEWBOO_INTERMEDIATE_STATE_POS    56
	#define NEWBOO_MOVEMENT_POS              57
	#define NEWBOO_SPEED_POS                 58
	#define NEWBOO_INCLINE_POS               59

#endif //NEWBOO_DEVICE_SPEC
