///
/// \file OPORP_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 852d4a6cefd149622aea350a9a65231ee141e600
///
/// \build 0520f87fe8e1dee1407962db309783bc8f845ab5
///
/// \date 2021-05-10 10:03:07
///
/// \author Dephy, Inc.

#ifndef OPORP_DEVICE_SPEC

	#define OPORP_DEVICE_SPEC
	#define OPORP_DEVICE_FIELD_COUNT 32

	#define OPORP_RIGID_POS                  0
	#define OPORP_ID_POS                     1
	#define OPORP_STATE_TIME_POS             2
	#define OPORP_ACCELX_POS                 3
	#define OPORP_ACCELY_POS                 4
	#define OPORP_ACCELZ_POS                 5
	#define OPORP_GYROX_POS                  6
	#define OPORP_GYROY_POS                  7
	#define OPORP_GYROZ_POS                  8
	#define OPORP_MOT_ANG_POS                9
	#define OPORP_MOT_VEL_POS                10
	#define OPORP_MOT_ACC_POS                11
	#define OPORP_MOT_CUR_POS                12
	#define OPORP_MOT_VOLT_POS               13
	#define OPORP_BATT_VOLT_POS              14
	#define OPORP_BATT_CURR_POS              15
	#define OPORP_TEMPERATURE_POS            16
	#define OPORP_STATUS_MN_POS              17
	#define OPORP_STATUS_EX_POS              18
	#define OPORP_STATUS_RE_POS              19
	#define OPORP_GENVAR_0_POS               20
	#define OPORP_GENVAR_1_POS               21
	#define OPORP_GENVAR_2_POS               22
	#define OPORP_GENVAR_3_POS               23
	#define OPORP_GENVAR_4_POS               24
	#define OPORP_GENVAR_5_POS               25
	#define OPORP_GENVAR_6_POS               26
	#define OPORP_GENVAR_7_POS               27
	#define OPORP_GENVAR_8_POS               28
	#define OPORP_GENVAR_9_POS               29
	#define OPORP_ANK_ANG_POS                30
	#define OPORP_ANK_VEL_POS                31

#endif //OPORP_DEVICE_SPEC
