///
/// \file XC00s_device_spec.c
///
/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// \core 715fdbea5c25474cf9a225c576edefc7751fb730
///
/// \build 17c065992c6af4db121d17092c314593c5710b6a
///
/// \date 2022-01-12 13:53:37
///
/// \author Dephy, Inc.

#ifndef XC00S_DEVICE_SPEC

	#define XC00S_DEVICE_SPEC
	#define XC00S_DEVICE_FIELD_COUNT 60

	#define XC00S_RIGID_POS                  0
	#define XC00S_ID_POS                     1
	#define XC00S_STATE_TIME_POS             2
	#define XC00S_ACCELX_POS                 3
	#define XC00S_ACCELY_POS                 4
	#define XC00S_ACCELZ_POS                 5
	#define XC00S_GYROX_POS                  6
	#define XC00S_GYROY_POS                  7
	#define XC00S_GYROZ_POS                  8
	#define XC00S_MOT_ANG_POS                9
	#define XC00S_MOT_VEL_POS                10
	#define XC00S_MOT_ACC_POS                11
	#define XC00S_MOT_CUR_POS                12
	#define XC00S_MOT_VOLT_POS               13
	#define XC00S_BATT_VOLT_POS              14
	#define XC00S_BATT_CURR_POS              15
	#define XC00S_TEMPERATURE_POS            16
	#define XC00S_STATUS_MN_POS              17
	#define XC00S_STATUS_EX_POS              18
	#define XC00S_STATUS_RE_POS              19
	#define XC00S_GENVAR_0_POS               20
	#define XC00S_GENVAR_1_POS               21
	#define XC00S_GENVAR_2_POS               22
	#define XC00S_GENVAR_3_POS               23
	#define XC00S_GENVAR_4_POS               24
	#define XC00S_GENVAR_5_POS               25
	#define XC00S_GENVAR_6_POS               26
	#define XC00S_GENVAR_7_POS               27
	#define XC00S_GENVAR_8_POS               28
	#define XC00S_GENVAR_9_POS               29
	#define XC00S_GENVAR_10_POS              30
	#define XC00S_GENVAR_11_POS              31
	#define XC00S_GENVAR_12_POS              32
	#define XC00S_GENVAR_13_POS              33
	#define XC00S_GENVAR_14_POS              34
	#define XC00S_ANK_ANG_POS                35
	#define XC00S_ANK_VEL_POS                36
	#define XC00S_SHANK_ANG_POS              37
	#define XC00S_SHANK_VEL_POS              38
	#define XC00S_GLOBAL_SHANK_ANG_POS       39
	#define XC00S_ANK_POS_X_POS              40
	#define XC00S_ANK_POS_Y_POS              41
	#define XC00S_ANK_POS_Z_POS              42
	#define XC00S_ANK_LINEAR_VEL_X_POS       43
	#define XC00S_ANK_LINEAR_VEL_Y_POS       44
	#define XC00S_ANK_LINEAR_VEL_Z_POS       45
	#define XC00S_MOT_FROM_ANK_POS           46
	#define XC00S_ANK_FROM_MOT_POS           47
	#define XC00S_TRANS_RATIO_POS            48
	#define XC00S_ANK_TORQUE_POS             49
	#define XC00S_AVG_ANK_TORQUE_POS         50
	#define XC00S_EXO_STEP_POWER_POS         51
	#define XC00S_BATTERY_STEP_POWER_POS     52
	#define XC00S_STEP_COUNT_POS             53
	#define XC00S_STEP_TIME_POS              54
	#define XC00S_GAIT_STATE_POS             55
	#define XC00S_INTERMEDIATE_STATE_POS     56
	#define XC00S_MOVEMENT_POS               57
	#define XC00S_SPEED_POS                  58
	#define XC00S_INCLINE_POS                59

#endif //XC00S_DEVICE_SPEC
