"""/*
 * HabsoluteState.py
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 * CORE:ecdab88c05df58d9ba18cb5e4d6e41c2f32b3e85
 * BUILD:065ba7c027caf247c3a01011370de5bc31a467f7
 *
 *
 * Specification File Created on: 2020-06-22 14:42:45
 * Author: Dephy, Inc.
 *
 */
"""
from ctypes import Structure, c_int

class HabsoluteState(Structure):
	_pack_ = 1
	_fields_ = [
		("habsolute", c_int),
		("id", c_int),
		("state_time", c_int),
		("ank_ang", c_int),
		("ank_vel", c_int),
		("adc_0", c_int),
		("adc_1", c_int),
		("adc_2", c_int),
		("adc_3", c_int),
		("adc_4", c_int),
		("adc_5", c_int),
		("adc_6", c_int),
		("adc_7", c_int),
		("genvar_0", c_int),
		("genvar_1", c_int),
		("genvar_2", c_int),
		("genvar_3", c_int),
		("status", c_int),
		("SystemTime", c_int)]
