"""
		///
		/// \file HabsoluteState.py
		///
		/// \brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
		///
		/// \core 700069e8da8284b565fc6f7fa52f563fd0d81fcf
		///
		/// \build dc0bdff105b62790206f5bbc9db0de68ea6fb403
		///
		/// \date 2020-06-22 14:42:45
		///
		/// \author Dephy, Inc.
		"""
from ctypes import Structure, c_int

class HabsoluteState(Structure):
	_pack_ = 1
	_fields_ = [
		("habsolute", c_int),
		("id", c_int),
		("state_time", c_int),
		("ank_ang", c_int),
		("ank_vel", c_int),
		("adc_0", c_int),
		("adc_1", c_int),
		("adc_2", c_int),
		("adc_3", c_int),
		("adc_4", c_int),
		("adc_5", c_int),
		("adc_6", c_int),
		("adc_7", c_int),
		("genvar_0", c_int),
		("genvar_1", c_int),
		("genvar_2", c_int),
		("genvar_3", c_int),
		("status", c_int),
		("SystemTime", c_int)]
