"""
///
/// @file HabsoluteState.py
///
/// @brief AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
///
/// @core 22b8056df896ab8048743e6c2f68f7fa9b2d48f8
///
/// @build 124d2903b0d2485f7864371fa16857f7eda2d9b9
///
/// @date 2020-06-22 14:42:45
///
/// @author Dephy, Inc.
"""
from ctypes import Structure, c_int

class HabsoluteState(Structure):
	_pack_ = 1
	_fields_ = [
		("habsolute", c_int),
		("id", c_int),
		("state_time", c_int),
		("ank_ang", c_int),
		("ank_vel", c_int),
		("adc_0", c_int),
		("adc_1", c_int),
		("adc_2", c_int),
		("adc_3", c_int),
		("adc_4", c_int),
		("adc_5", c_int),
		("adc_6", c_int),
		("adc_7", c_int),
		("genvar_0", c_int),
		("genvar_1", c_int),
		("genvar_2", c_int),
		("genvar_3", c_int),
		("status", c_int),
		("SystemTime", c_int)]
