FLEXSEA_PLAN_1 = 10
FLEXSEA_MANAGE_1 = 20
FLEXSEA_EXECUTE_1 = 40

CTRL_NONE = 0
CTRL_OPEN = 1
CTRL_POSITION = 2
CTRL_CURRENT = 3
CTRL_IMPEDANCE = 4
CTRL_CUSTOM = 5
CTRL_MEASRES = 6

KEEP = 0
CHANGE = 1
SYS_NORMAL = 0
SYS_DISABLE_FSM2 = 1
CALIBRATION_FIND_POLES = 1
RIGHT = 0
LEFT = 1

FX_NUM_PORTS = 4
# device field ids for rigid
FX_DEVTYPE = 0
FX_DEVTID = 1
FX_STATETIME = 2
FX_ACCELX = 3
FX_ACCELY = 4
FX_ACCELZ = 5
FX_GYROX = 6
FX_GYROY  =  7
FX_GYROZ = 8
FX_ENC_ANG = 9
FX_ENC_VEL = 10
FX_ENC_ACC = 11
FX_MOT_CURR = 12
FX_MOT_VOLT = 13
FX_BATT_VOLT = 14
FX_BATT_CURR = 15
FX_BATT_TEMP = 16
FX_BATT_STATUS = 17
FX_GEN_VAR_BASE = 18
FX_GEN_VAR_0 = FX_GEN_VAR_BASE + 0
FX_GEN_VAR_1 = FX_GEN_VAR_BASE + 1
FX_GEN_VAR_2 = FX_GEN_VAR_BASE + 2
FX_GEN_VAR_3 = FX_GEN_VAR_BASE + 3
FX_GEN_VAR_4 = FX_GEN_VAR_BASE + 4
FX_GEN_VAR_5 = FX_GEN_VAR_BASE + 5
FX_GEN_VAR_6 = FX_GEN_VAR_BASE + 6
FX_GEN_VAR_7 = FX_GEN_VAR_BASE + 7
FX_GEN_VAR_8 = FX_GEN_VAR_BASE + 8
FX_GEN_VAR_9 = FX_GEN_VAR_BASE + 9
FX_ANKLE_ANG = 28
FX_ANKLE_ANG_VEL = 29


FX_VALID_FREQUENCIES = [1, 5, 10, 20, 33, 50, 100, 200, 300, 500]