- name: "pre-commit"

  on:
    pull_request:
    push:
      branches: [master, develop]

  jobs:
    pre-commit:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

- name: Publish to PyPI
  on:
    push:
      branches: [master, develop]
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
    packages_dir: Python/flexsea/
