name: "nox"

on:
  pull_request:
  push:

jobs:
  run_nox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Nox
        uses: daisylb/setup-nox@v2.1.0

      - name: Run Nox
        run: nox
